default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *default
  database: slack_development

test:
  <<: *default
  database: slack_test

production:
  <<: *default
  database: slack_production
